#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGS = ROOT / "logs"
OUTPUT = ROOT / "report" / "server_results.tex"


def summarize(processes: int) -> tuple[str, str]:
    paths = sorted(LOGS.glob(f"{processes}p-*.log"))
    passed = sum("TEST_RESULT PASS" in path.read_text(errors="replace") for path in paths)
    status = "PASS" if len(paths) == processes and passed == processes else "FAIL"
    if not paths:
        status = "Not yet executed"
    return status, f"{passed}/{processes}"


two_status, two_ranks = summarize(2)
four_status, four_ranks = summarize(4)
OUTPUT.write_text(
    "% Generated by scripts/summarize_server_logs.py.\n"
    f"\\newcommand{{\\TwoProcessServerStatus}}{{{two_status}}}\n"
    f"\\newcommand{{\\FourProcessServerStatus}}{{{four_status}}}\n"
    f"\\newcommand{{\\TwoProcessPassingRanks}}{{{two_ranks}}}\n"
    f"\\newcommand{{\\FourProcessPassingRanks}}{{{four_ranks}}}\n"
)
print(f"Wrote {OUTPUT}")
